name: Gather new plugins
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 2-30/2 * *'  # every other day

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.2.2

      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16

      - run: |
          nix develop .#ci
          ./new-plugins.sh

      - name: Commit & Push changes
        uses: actions-js/push@5a7cbd780d82c0c937b5977586e641b2fd94acc5 # v1.5
        with:
          branch: 'main'
          message: "chore(flake): Get new plugins"
          github_token: ${{ secrets.GITHUB_TOKEN }}
